language: android
jdk: oraclejdk8
sudo: false

android:
  components:
#    - tools
#    - platform-tools
#    - tools
#    - build-tools-22.0
#    - android-22

#    - platform-tools
    - build-tools-22.0.1
    - android-22
    - sys-img-armeabi-v7a-android-22

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

#
#licenses:
#  - 'android-sdk-preview-license-.+'
#  - 'android-sdk-license-.+'
#  - 'google-gdk-license-.+'

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before-install:
  - chmod +x gradlew

notifications:
  email:
    recipients:
      - curatchaj@gmail.com
    on_success: never
    on_failure: change