language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

    - sys-img-armeabi-v7a-android-22

#
#licenses:
#  - 'android-sdk-preview-license-.+'
#  - 'android-sdk-license-.+'
#  - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

before-install:
  - chmod +x gradlew

notifications:
  email:
    recipients:
      - curatchaj@gmail.com
    on_success: never
    on_failure: change